version: "3.3"
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
  api:
    image: ahsantahseen/ahsan_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: api
    expose:
      - 5000
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    expose:
      - '80'
      - '443'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
volumes:
  db_data:


